[project]
name = "open-ai-gym"
version = "0.1.0"
description = ""
requires-python = ">=3.11"
dependencies = [
  "abstract-base-classes",
  "tensorflow>=2.6.0",
  "numpy>=1.26.3",
  "gymnasium[box2d,atari,mujoco]>=0.29.1",
]

[tool.uv]
package = true

[tool.uv.sources]
abstract-base-classes = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["open_ai_gym"]
