[project]
name = "cli-tools"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
authors = [
  { name = "icarus64", email = "ellishogan95@gmail.com" },
]
dependencies = [
  "Pillow>=10.0.0",
]

[tool.uv]
package = true

[tool.hatch.build.targets.wheel]
packages = ["cli_tools"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
