[project]
name = "anki-tools"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
authors = [
  { name = "icarus64", email = "ellishogan95@gmail.com" },
]
dependencies = [
  "requests>=2.28.0",
  "anki",
]

[tool.uv]
package = true

[tool.hatch.build.targets.wheel]
packages = ["anki_tools"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["pytest"]

[tool.pytest.ini_options]
testpaths = ["tests"]
