name: Sync Repositories

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        path: daedalus-mono

    - name: Build Maze Runner Mono
      run: |
        git clone https://${{ secrets.PAT }}@github.com/icarus612/maze-runner-mono.git

    - name: Remove old content
      run: |
        rm -rf maze-runner-mono/apps/*
        rm -rf maze-runner-mono/libs/*

    - name: Copy content
      run: |
        cp -R  daedalus-mono/apps/flask/maze-runner maze-runner-mono/apps/flask 
        cp -R  daedalus-mono/apps/next/maze-runner maze-runner-mono/apps/next

        cp -R  daedalus-mono/libs/python/maze-runner maze-runner-mono/libs/python
        cp -R  daedalus-mono/libs/javascript/node/maze-runner maze-runner-mono/libs/javascript
        cp -R  daedalus-mono/libs/javascript/react/maze-runner maze-runner-mono/libs/react-js 

    - name: Commit and push
      run: |
        cd maze-runner-mono
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Sync content from source repository"
        git push https://${{ secrets.PAT }}@github.com/icarus612/maze-runner-mono.git