name: Sync Repositories

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        path: daedalus-mono

    - name: Build Maze Runner Mono
      run: | 
        EX_FILE=daedalus-mono/libs/bash/github-actions/build-maze-runner.sh
        chmod +x $EX_FILE
        ./$EX_FILE
        